name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
     
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jenkis94
          password: dckr_pat_w1KkT0ARS0bdkOuVK9-lP4fIJEw
 
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2
        with:
        
          tags: jenkis94/mea4_03_rides:backend_latest
          push: true
          
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2
        with:
          working-directory: src/main/ride_sharing_webbapp/
          tags: jenkis94/mea4_03_rides:frontend_latest
          push: true
